### ISSUE TITLE
CSS 盒模型和 DOCTYPE

### ISSUE THREAD

**Issue by lxfriday** [lxfriday/give-me-job#41]

**Comment by lxfriday** [comment]
## CSS 基础盒模型

CSS 盒模型是页面布局的基础。

当对一个文档进行布局的时候，浏览器的渲染引擎会根据标准之一的 CSS 基础框盒模型（CSS basic box model），将所有元素表示为一个个矩形的盒子（box）。CSS 决定这些盒子的大小、位置以及属性（例如颜色、背景、边框尺寸…）。

每个盒子由四个部分（或称区域）组成，分别为：**内容区域 content area**、**内边距区域 padding area**、**边框区域 border area** 、**外边距区域 margin area**，分别对应 `width、height`、`padding`、`border`、`margin`。

注意 `box-sizing` 这个 CSS 属性。

1. `content-box` （W3C 盒模型）是默认值。如果你设置一个元素的宽为 100px，那么这个元素的内容区会有 100px 宽，并且任何边框和内边距的宽度都会被增加到最后绘制出来的元素宽度中。也就是说，**最终盒子的宽高 >= 设置的宽高**。
2. `border-box` （IE 盒模型）告诉浏览器：你想要设置的边框和内边距的值是包含在 width 内的。也就是说，如果你将一个元素的 width 设为 100px，那么这 100px 会包含它的 border 和 padding，内容区的实际宽度是 width 减去(border + padding)的值。大多数情况下，这使得我们更容易地设定一个元素的宽高。

看下面的例子。

```html
<div class="content-box">Content box</div>
<br>
<div class="border-box">Border box</div>
```

```css
div {
  width: 160px;
  height: 80px;
  padding: 20px;
  border: 8px solid red;
  background: yellow;
}

.content-box { 
  box-sizing: content-box; 
  /* Total width: 160px + (2 * 20px) + (2 * 8px) = 216px
     Total height: 80px + (2 * 20px) + (2 * 8px) = 136px
     Content box width: 160px
     Content box height: 80px */
}

.border-box { 
  box-sizing: border-box;
  /* Total width: 160px
     Total height: 80px
     Content box width: 160px - (2 * 20px) - (2 * 8px) = 104px
     Content box height: 80px - (2 * 20px) - (2 * 8px) = 24px */
}
```


![image](https://qiniu1.lxfriday.xyz/blog/image_20191120233657.png)

从结果可以看得比较明白，`border-box` 的总宽高不会超过设定的 `width` 和 `height`，而 `content-box` 的大小是不确定的，会受到 `border` 和 `padding` 影响。

参考：

1. [CSS 基础框盒模型介绍](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)
